-----------------------------------
-- Trust: Aaev
-- Custom Trust Generated by TrustEditor
-- Jobs: DNC/COR
-----------------------------------
require("scripts/globals/trust")
require("scripts/globals/magic")

---@type TSpellTrust
local spellObject = {}

spellObject.onMagicCastingCheck = function(caster, target, spell)
    return xi.trust.canCast(caster, spell)
end

spellObject.onSpellCast = function(caster, target, spell)
    return xi.trust.spawn(caster, spell)
end

spellObject.onMobSpawn = function(mob)
    mob:setAutoAttackEnabled(true)

    mob:addMod(xi.mod.CHR, 15)
    mob:addMod(xi.mod.DEX, 15)
    mob:addMod(xi.mod.EVA, 10)


    -- Faux Gear Look
    mob:setLook({ main = 21966, sub = 17609, ranged = 21392, ammo = 21295, head = 16116, body = 23489, hands = 23230, legs = 23293, feet = 23676 })
    -- Gear Mods (from item_mods.sql)
    mob:addMod(xi.mod.ITEM_ADDEFFECT_TYPE, 10) -- main: zanmato_+1
    mob:addMod(xi.mod.ITEM_SUBEFFECT, 7) -- main: zanmato_+1
    mob:addMod(xi.mod.ITEM_ADDEFFECT_CHANCE, 5) -- main: zanmato_+1
    mob:addMod(xi.mod.AUTOMATON_LVL_BONUS, 20) -- ranged: animator_z
    mob:addMod(xi.mod.1, 19) -- head: valkyries_hat
    mob:addMod(xi.mod.MP, 40) -- head: valkyries_hat
    mob:addMod(xi.mod.ENMITY, -4) -- head: valkyries_hat
    mob:addMod(xi.mod.MACC, 6) -- head: valkyries_hat
    mob:addMod(xi.mod.DMGPHYS, 400) -- head: valkyries_hat
    mob:addMod(xi.mod.1, 155) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.HP, 127) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.MP, 139) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.STR, 30) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.DEX, 35) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.VIT, 35) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.AGI, 30) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.INT, 45) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.MND, 48) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.CHR, 39) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.ACC, 64) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.MDEF, 11) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.MACC, 64) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.MEVA, 130) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.EVA, 91) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.HEALING, 34) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.AFFLATUS_SOLACE, 21) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.REFRESH, 5) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.REGEN, 9) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.HASTE_GEAR, 300) -- body: ebers_bliaut_+3
    mob:addMod(xi.mod.1, 124) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.HP, 47) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.STR, 19) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.DEX, 42) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.VIT, 42) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.AGI, 18) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.INT, 16) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.MND, 34) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.CHR, 26) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.ATT, 52) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.RATT, 52) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.ACC, 52) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.RACC, 52) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.MDEF, 4) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.MACC, 52) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.MEVA, 72) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.EVA, 64) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.HASTE_GEAR, 400) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.ALL_WSDMG_FIRST_HIT, 8) -- hands: kasuga_kote_+2
    mob:addMod(xi.mod.1, 149) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.HP, 72) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.MP, 61) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.STR, 48) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.VIT, 30) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.AGI, 25) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.INT, 36) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.MND, 24) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.CHR, 21) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.ATT, 63) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.ACC, 53) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.MDEF, 7) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.MACC, 53) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.MEVA, 109) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.EVA, 64) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.DARK, 25) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.DMG, -1100) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.HASTE_GEAR, 500) -- legs: heathens_flanchard_+2
    mob:addMod(xi.mod.1, 88) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.HP, 33) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.STR, 24) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.DEX, 34) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.VIT, 20) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.AGI, 51) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.MND, 22) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.CHR, 40) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.RATT, 81) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.RACC, 36) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.ENMITY, -8) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.MDEF, 7) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.MACC, 36) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.MEVA, 89) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.EVA, 92) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.CRITHITRATE, 8) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.RAPID_SHOT, 10) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.HASTE_GEAR, 400) -- feet: arcadian_socks_+3
    mob:addMod(xi.mod.MACC, 30) -- neck: bagua_charm_+2
    mob:addMod(xi.mod.GEOMANCY_BONUS, 7) -- neck: bagua_charm_+2
    mob:addMod(xi.mod.1, 13) -- waist: gevaudan_belt
    mob:addMod(xi.mod.ATT, 10) -- waist: gevaudan_belt
    mob:addMod(xi.mod.ACC, 10) -- waist: gevaudan_belt
    mob:addMod(xi.mod.ATT, 10) -- ear2: balder_earring_+1
    mob:addMod(xi.mod.EVA, 10) -- ear2: balder_earring_+1
    mob:addMod(xi.mod.STORETP, 3) -- ear2: balder_earring_+1
    mob:addMod(xi.mod.INT, 2) -- ring1: acumen_ring
    mob:addMod(xi.mod.MATT, 4) -- ring1: acumen_ring
    mob:addMod(xi.mod.ACC, 11) -- ring2: cacoethic_ring_+1
    mob:addMod(xi.mod.RACC, 16) -- ring2: cacoethic_ring_+1
    mob:addMod(xi.mod.1, 21) -- back: aput_mantle_+1
    mob:addMod(xi.mod.MP, 30) -- back: aput_mantle_+1
    mob:addMod(xi.mod.ICE_MEVA, 11) -- back: aput_mantle_+1
    mob:addMod(xi.mod.MACC, 9) -- back: aput_mantle_+1
    mob:addMod(xi.mod.MAGIC_DAMAGE, 15) -- back: aput_mantle_+1
    mob:addGambit(ai.t.TARGET, { ai.c.NO_SAMBA, 0 }, { ai.r.JA, ai.s.BEST_SAMBA, 0 })
    mob:addGambit(ai.t.TARGET, { ai.c.ALWAYS, 0 }, { ai.r.JA, ai.s.SPECIFIC, xi.ja.BOX_STEP })
    mob:addGambit(ai.t.PARTY, { ai.c.HPP_LT, 55 }, { ai.r.JA, ai.s.SPECIFIC, xi.ja.CURING_WALTZ_IV })
    mob:addGambit(ai.t.SELF, { ai.c.TP_GTE, 1250 }, { ai.r.WS, ai.s.HIGHEST, 0 })

    mob:setTrustTPSkillSettings(ai.tp.CLOSER_UNTIL_TP, ai.s.HIGHEST, 1250)

    -- Custom Code
    
end

spellObject.onMobDespawn = function(mob)
    xi.trust.message(mob, xi.trust.messageOffset.DESPAWN)
end

spellObject.onMobDeath = function(mob)
    xi.trust.message(mob, xi.trust.messageOffset.DEATH)
end

return spellObject
