-----------------------------------
-- Trust: Aaev
-----------------------------------
---@type TSpellTrust
local spellObject = {}

spellObject.onMagicCastingCheck = function(caster, target, spell)
    return xi.trust.canCast(caster, spell)
end

spellObject.onSpellCast = function(caster, target, spell)
    return xi.trust.spawn(caster, spell)
end

spellObject.onMobSpawn = function(mob)
    mob:setAutoAttackEnabled(true)

    mob:addMod(xi.mod.CHR, 15)
    mob:addMod(xi.mod.DEX, 15)
    mob:addMod(xi.mod.EVA, 10)
    mob:addMod(xi.mod.ITEM_ADDEFFECT_TYPE, 10)
    mob:addMod(xi.mod.ITEM_SUBEFFECT, 7)
    mob:addMod(xi.mod.ITEM_ADDEFFECT_CHANCE, 5)
    mob:addMod(xi.mod.AUTOMATON_LVL_BONUS, 20)
    mob:addMod(xi.mod.1, 19)
    mob:addMod(xi.mod.MP, 40)
    mob:addMod(xi.mod.ENMITY, -4)
    mob:addMod(xi.mod.MACC, 6)
    mob:addMod(xi.mod.DMGPHYS, 400)
    mob:addMod(xi.mod.1, 155)
    mob:addMod(xi.mod.HP, 127)
    mob:addMod(xi.mod.MP, 139)
    mob:addMod(xi.mod.STR, 30)
    mob:addMod(xi.mod.DEX, 35)
    mob:addMod(xi.mod.VIT, 35)
    mob:addMod(xi.mod.AGI, 30)
    mob:addMod(xi.mod.INT, 45)
    mob:addMod(xi.mod.MND, 48)
    mob:addMod(xi.mod.CHR, 39)
    mob:addMod(xi.mod.ACC, 64)
    mob:addMod(xi.mod.MDEF, 11)
    mob:addMod(xi.mod.MACC, 64)
    mob:addMod(xi.mod.MEVA, 130)
    mob:addMod(xi.mod.EVA, 91)
    mob:addMod(xi.mod.HEALING, 34)
    mob:addMod(xi.mod.AFFLATUS_SOLACE, 21)
    mob:addMod(xi.mod.REFRESH, 5)
    mob:addMod(xi.mod.REGEN, 9)
    mob:addMod(xi.mod.HASTE_GEAR, 300)
    mob:addMod(xi.mod.1, 124)
    mob:addMod(xi.mod.HP, 47)
    mob:addMod(xi.mod.STR, 19)
    mob:addMod(xi.mod.DEX, 42)
    mob:addMod(xi.mod.VIT, 42)
    mob:addMod(xi.mod.AGI, 18)
    mob:addMod(xi.mod.INT, 16)
    mob:addMod(xi.mod.MND, 34)
    mob:addMod(xi.mod.CHR, 26)
    mob:addMod(xi.mod.ATT, 52)
    mob:addMod(xi.mod.RATT, 52)
    mob:addMod(xi.mod.ACC, 52)
    mob:addMod(xi.mod.RACC, 52)
    mob:addMod(xi.mod.MDEF, 4)
    mob:addMod(xi.mod.MACC, 52)
    mob:addMod(xi.mod.MEVA, 72)
    mob:addMod(xi.mod.EVA, 64)
    mob:addMod(xi.mod.HASTE_GEAR, 400)
    mob:addMod(xi.mod.ALL_WSDMG_FIRST_HIT, 8)
    mob:addMod(xi.mod.1, 149)
    mob:addMod(xi.mod.HP, 72)
    mob:addMod(xi.mod.MP, 61)
    mob:addMod(xi.mod.STR, 48)
    mob:addMod(xi.mod.VIT, 30)
    mob:addMod(xi.mod.AGI, 25)
    mob:addMod(xi.mod.INT, 36)
    mob:addMod(xi.mod.MND, 24)
    mob:addMod(xi.mod.CHR, 21)
    mob:addMod(xi.mod.ATT, 63)
    mob:addMod(xi.mod.ACC, 53)
    mob:addMod(xi.mod.MDEF, 7)
    mob:addMod(xi.mod.MACC, 53)
    mob:addMod(xi.mod.MEVA, 109)
    mob:addMod(xi.mod.EVA, 64)
    mob:addMod(xi.mod.DARK, 25)
    mob:addMod(xi.mod.DMG, -1100)
    mob:addMod(xi.mod.HASTE_GEAR, 500)
    mob:addMod(xi.mod.1, 88)
    mob:addMod(xi.mod.HP, 33)
    mob:addMod(xi.mod.STR, 24)
    mob:addMod(xi.mod.DEX, 34)
    mob:addMod(xi.mod.VIT, 20)
    mob:addMod(xi.mod.AGI, 51)
    mob:addMod(xi.mod.MND, 22)
    mob:addMod(xi.mod.CHR, 40)
    mob:addMod(xi.mod.RATT, 81)
    mob:addMod(xi.mod.RACC, 36)
    mob:addMod(xi.mod.ENMITY, -8)
    mob:addMod(xi.mod.MDEF, 7)
    mob:addMod(xi.mod.MACC, 36)
    mob:addMod(xi.mod.MEVA, 89)
    mob:addMod(xi.mod.EVA, 92)
    mob:addMod(xi.mod.CRITHITRATE, 8)
    mob:addMod(xi.mod.RAPID_SHOT, 10)
    mob:addMod(xi.mod.HASTE_GEAR, 400)
    mob:addMod(xi.mod.MACC, 30)
    mob:addMod(xi.mod.GEOMANCY_BONUS, 7)
    mob:addMod(xi.mod.1, 13)
    mob:addMod(xi.mod.ATT, 10)
    mob:addMod(xi.mod.ACC, 10)
    mob:addMod(xi.mod.ATT, 10)
    mob:addMod(xi.mod.EVA, 10)
    mob:addMod(xi.mod.STORETP, 3)
    mob:addMod(xi.mod.INT, 2)
    mob:addMod(xi.mod.MATT, 4)
    mob:addMod(xi.mod.ACC, 11)
    mob:addMod(xi.mod.RACC, 16)
    mob:addMod(xi.mod.1, 21)
    mob:addMod(xi.mod.MP, 30)
    mob:addMod(xi.mod.ICE_MEVA, 11)
    mob:addMod(xi.mod.MACC, 9)
    mob:addMod(xi.mod.MAGIC_DAMAGE, 15)


    -- Faux Gear Look
    mob:setLook({ main = 21966, sub = 17609, ranged = 21392, ammo = 21295, head = 16116, body = 23489, hands = 23230, legs = 23293, feet = 23676 })
    mob:addGambit(ai.t.TARGET, { ai.c.NO_SAMBA, 0 }, { ai.r.JA, ai.s.BEST_SAMBA, 0 })
    mob:addGambit(ai.t.TARGET, { ai.c.ALWAYS, 0 }, { ai.r.JA, ai.s.SPECIFIC, xi.ja.BOX_STEP })
    mob:addGambit(ai.t.PARTY, { ai.c.HPP_LT, 55 }, { ai.r.JA, ai.s.SPECIFIC, xi.ja.CURING_WALTZ_IV })
    mob:addGambit(ai.t.SELF, { ai.c.TP_GTE, 1250 }, { ai.r.WS, ai.s.HIGHEST, 0 })

    mob:setTrustTPSkillSettings(ai.tp.CLOSER_UNTIL_TP, ai.s.HIGHEST, 1250)

    -- Custom Code
    
end

spellObject.onMobDespawn = function(mob)
    xi.trust.message(mob, xi.trust.messageOffset.DESPAWN)
end

spellObject.onMobDeath = function(mob)
    xi.trust.message(mob, xi.trust.messageOffset.DEATH)
end

return spellObject
