#!/usr/bin/env python3
"""
Extract spell lists from spell_list.sql using the jobs bitmask as the source of truth.

This is the CORRECT way to generate spell lists - using actual spell learn data
from the database instead of guessing from directory structures.

Each spell in spell_list.sql has a 'jobs' field (binary) that indicates which jobs
can learn that spell. We decode this bitmask to build job-specific spell lists.

Main/Sub job handling:
- Main job: Gets ALL spells (including level 99 spells)
- Sub job: Gets only spells up to level 59 (game mechanic)
- Both directions created: JOB1_JOB2 and JOB2_JOB1 are different
"""

import re
from pathlib import Path
from collections import defaultdict
from itertools import combinations

# Job ID to name mapping (must match xi.job constants)
JOB_ID_TO_NAME = {
    1: "WAR", 2: "MNK", 3: "WHM", 4: "BLM", 5: "RDM", 6: "THF",
    7: "PLD", 8: "DRK", 9: "BST", 10: "BRD", 11: "RNG", 12: "SAM",
    13: "NIN", 14: "DRG", 15: "SMN", 16: "BLU", 17: "COR", 18: "PUP",
    19: "DNC", 20: "SCH", 21: "GEO", 22: "RUN", 23: "MON",
}

NAME_TO_JOB_ID = {v: k for k, v in JOB_ID_TO_NAME.items()}

# Magic jobs we support in the trust editor
MAGIC_JOBS = ['WHM', 'BLM', 'RDM', 'BRD', 'SMN', 'BLU', 'NIN', 'RUN', 'GEO', 'DRK', 'PLD', 'SCH', 'BST']

def hex_to_binary(hex_str):
    """Convert hex string to binary list of job bits."""
    # Remove '0x' prefix if present
    if hex_str.startswith('0x'):
        hex_str = hex_str[2:]

    # Convert hex to integer
    value = int(hex_str, 16)

    # Extract bits for each job (bits 0-22 = jobs 1-23)
    jobs = []
    for job_id in range(1, 24):
        if value & (1 << (job_id - 1)):
            jobs.append(job_id)

    return jobs

def extract_spell_lists_from_sql():
    """Extract spell lists from spell_list.sql using jobs bitmask."""
    spell_lists = defaultdict(set)  # job_name -> set of spell_ids
    spell_info = {}  # spell_id -> (name, jobs_list)

    sql_file = Path('/Volumes/NVMe/git/LSBserver/sql/spell_list.sql')
    if not sql_file.exists():
        print("Error: spell_list.sql not found")
        return {}, {}

    content = sql_file.read_text()

    # Pattern to match spell_list INSERT statements
    # INSERT INTO `spell_list` VALUES (spellid,'name',jobs_hex,...)
    pattern = r"INSERT INTO `spell_list` VALUES \((\d+),'([^']*)',0x([a-f0-9]+),"

    # Trust spell IDs that should never be in job spell lists
    # Trusts cannot summon other trusts
    trust_spell_ids = set(range(900, 1000)) | set(range(1004, 1020))

    spell_count = 0
    for match in re.finditer(pattern, content, re.IGNORECASE):
        spell_id = int(match.group(1))
        spell_name = match.group(2)
        jobs_hex = match.group(3)

        # Skip trust spell IDs - they should not be in any job's spell list
        if spell_id in trust_spell_ids:
            continue

        # Decode jobs bitmask
        job_ids = hex_to_binary('0x' + jobs_hex)

        if job_ids:
            spell_count += 1
            spell_info[spell_id] = (spell_name, job_ids)

            # Add this spell to each job that can learn it
            for job_id in job_ids:
                job_name = JOB_ID_TO_NAME.get(job_id)
                if job_name:
                    spell_lists[job_name].add(spell_id)

    print(f"Extracted {spell_count} spells from spell_list.sql")

    # Convert sets to sorted lists
    for job_name in spell_lists:
        spell_lists[job_name] = sorted(list(spell_lists[job_name]))

    return spell_lists, spell_info

def extract_spell_levels():
    """Extract spell levels from mob_spell_lists.sql using Beastmen lists."""
    spell_levels = {}
    sql_file = Path('/Volumes/NVMe/git/LSBserver/sql/mob_spell_lists.sql')

    if sql_file.exists():
        content = sql_file.read_text()
        for match in re.finditer(
            r"INSERT INTO `mob_spell_lists` VALUES \('Beastmen_[A-Z]+',\d+,(\d+),(\d+),(\d+)\)",
            content
        ):
            spell_id, min_level, max_level = match.groups()
            spell_id = int(spell_id)
            if spell_id not in spell_levels:
                spell_levels[spell_id] = (int(min_level), int(max_level))

    return spell_levels

def generate_python_code(spell_lists, spell_levels):
    """Generate Python code for spell lists with proper main/sub job handling."""
    lines = []
    lines.append("# ============================================================================")
    lines.append("# AUTO-GENERATED SPELL LISTS FOR JOBS AND JOB COMBINATIONS")
    lines.append("# Generated by generate_spell_lists_from_sql.py")
    lines.append("# Source: spell_list.sql jobs bitmask (source of truth)")
    lines.append("# ")
    lines.append("# These lists contain spell IDs that each job can actually learn.")
    lines.append("# For main/sub combinations: main job gets ALL spells, sub job limited to level 59.")
    lines.append("# ============================================================================\n")

    # Single job spell lists
    lines.append("# Single Job Spell Lists")
    lines.append("# ----------------------\n")

    for job_name in sorted(MAGIC_JOBS):
        spell_ids = spell_lists.get(job_name, [])
        var_name = f"{job_name}_SPELLS"

        lines.append(f"{var_name} = [")
        if spell_ids:
            for i, spell_id in enumerate(spell_ids):
                if i % 12 == 0:
                    lines.append("     ")
                lines[-1] += f"{spell_id:4d},"
            # Remove trailing comma from last line
            lines[-1] = lines[-1].rstrip(',')
        lines.append("]")
        lines.append("")

    # Job combination spell lists (both directions, with sub-job level cap)
    lines.append("\n# Job Combination Spell Lists (Main Job + Sub Job)")
    lines.append("# -----------------------------------------------")
    lines.append("# Main job: ALL spells | Sub job: spells level 59 and below\n")

    for job1_name, job2_name in sorted(combinations(MAGIC_JOBS, 2)):
        # Both directions: job1_job2 (job1 is main) and job2_job1 (job2 is main)
        for main_job, sub_job in [(job1_name, job2_name), (job2_name, job1_name)]:
            combo_name = f"{main_job}_{sub_job}_SPELLS"
            main_spells = set(spell_lists.get(main_job, []))
            sub_spells = set(spell_lists.get(sub_job, []))

            # Filter sub-job spells to level 59 and below
            sub_spells_lv59 = {sid for sid in sub_spells if spell_levels.get(sid, (1, 99))[1] <= 59}

            combined_spells = sorted(list(main_spells | sub_spells_lv59))

            lines.append(f"{combo_name} = [")
            if combined_spells:
                for i, spell_id in enumerate(combined_spells):
                    if i % 12 == 0:
                        lines.append("     ")
                    lines[-1] += f"{spell_id:4d},"
                # Remove trailing comma from last line
                lines[-1] = lines[-1].rstrip(',')
            lines.append("]")
            lines.append("")

    return "\n".join(lines), spell_lists

def generate_sql_insertions(spell_lists, spell_levels, start_list_id=566):
    """Generate SQL INSERT statements with proper level ranges and main/sub handling."""
    lines = []
    list_id = start_list_id
    list_id_map = {}

    lines.append("-- ============================================================================")
    lines.append("-- AUTO-GENERATED SPELL LISTS FOR JOBS AND JOB COMBINATIONS")
    lines.append("-- Generated by generate_spell_lists_from_sql.py")
    lines.append("-- Source: spell_list.sql jobs bitmask")
    lines.append("-- Main/Sub: Main job gets ALL spells, sub job limited to level 59")
    lines.append("-- ============================================================================\n")

    # Single job lists
    lines.append("-- Single Job Spell Lists")
    lines.append("-- =====================\n")

    stats = {'with_levels': 0, 'without_levels': 0}

    for job_name in sorted(MAGIC_JOBS):
        spell_ids = spell_lists.get(job_name, [])
        list_id_map[job_name] = list_id

        lines.append(f"-- {job_name} ({list_id})")
        for spell_id in spell_ids:
            if spell_id in spell_levels:
                min_lvl, max_lvl = spell_levels[spell_id]
                stats['with_levels'] += 1
            else:
                min_lvl, max_lvl = 1, 99
                stats['without_levels'] += 1
            lines.append(f"INSERT INTO `mob_spell_lists` VALUES ('{job_name}',{list_id},{spell_id},{min_lvl},{max_lvl});")
        lines.append("")
        list_id += 1

    # Job combination lists with proper main/sub handling
    lines.append("\n-- Job Combination Spell Lists (Main Job + Sub Job)")
    lines.append("-- ================================================")
    lines.append("-- Main job: ALL spells | Sub job: spells level 59 and below\n")

    for job1_name, job2_name in sorted(combinations(MAGIC_JOBS, 2)):
        # Both directions
        for main_job, sub_job in [(job1_name, job2_name), (job2_name, job1_name)]:
            combo_name = f"{main_job}_{sub_job}"
            main_spells = set(spell_lists.get(main_job, []))
            sub_spells = set(spell_lists.get(sub_job, []))

            # Filter sub-job spells to level 59 and below
            sub_spells_lv59 = {sid for sid in sub_spells if spell_levels.get(sid, (1, 99))[1] <= 59}

            combined_spells = sorted(list(main_spells | sub_spells_lv59))

            list_id_map[combo_name] = list_id

            lines.append(f"-- {combo_name} ({list_id})")
            for spell_id in combined_spells:
                if spell_id in spell_levels:
                    min_lvl, max_lvl = spell_levels[spell_id]
                    stats['with_levels'] += 1
                else:
                    min_lvl, max_lvl = 1, 99
                    stats['without_levels'] += 1
                lines.append(f"INSERT INTO `mob_spell_lists` VALUES ('{combo_name}',{list_id},{spell_id},{min_lvl},{max_lvl});")
            lines.append("")
            list_id += 1

    lines.append(f"-- Total new spell lists added: {list_id - start_list_id}")
    lines.append(f"-- IDs used: {start_list_id} to {list_id - 1}")
    lines.append(f"-- Spells with level data: {stats['with_levels']}")
    lines.append(f"-- Spells without level data (using defaults): {stats['without_levels']}")

    return "\n".join(lines), list_id_map, list_id, stats

def main():
    print("=" * 80)
    print("EXTRACTING SPELL LISTS FROM spell_list.sql (SOURCE OF TRUTH)")
    print("=" * 80)
    print()

    print("Step 1: Extracting spell lists from spell_list.sql...")
    spell_lists, spell_info = extract_spell_lists_from_sql()
    print(f"  Found spells for {len(spell_lists)} jobs\n")

    print("Step 2: Extracting spell levels from mob_spell_lists.sql...")
    spell_levels = extract_spell_levels()
    print(f"  Found level data for {len(spell_levels)} spells\n")

    if spell_lists:
        print("Spell counts by job:")
        for job_name in sorted(MAGIC_JOBS):
            count = len(spell_lists.get(job_name, []))
            print(f"  {job_name:5} - {count:3} spells")
        print()

    print("Step 3: Generating Python code...")
    python_code, _ = generate_python_code(spell_lists, spell_levels)

    output_py = Path("/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust/job_spell_lists_corrected.py")
    output_py.write_text(python_code)
    print(f"  Written to: {output_py}\n")

    print("Step 4: Generating SQL insertions...")
    sql_code, list_id_map, next_id, stats = generate_sql_insertions(spell_lists, spell_levels)

    output_sql = Path("/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust/spell_lists_corrected.sql")
    output_sql.write_text(sql_code)
    print(f"  Written to: {output_sql}")
    print(f"  Total spell lists: {len(list_id_map)}")
    print(f"  ID range: 566 to {next_id - 1}")
    print(f"  Spells with level data: {stats['with_levels']:,}")
    print(f"  Spells with defaults: {stats['without_levels']:,}\n")

    print("=" * 80)
    print("NEXT STEPS:")
    print("=" * 80)
    print("1. Review the corrected spell lists:")
    print(f"   - Python: {output_py}")
    print(f"   - SQL: {output_sql}")
    print()
    print("2. Back up trust_editor.py and spell_lists for SQL:")
    print("   cp trust_editor.py trust_editor.py.backup")
    print("   cp /Volumes/NVMe/git/LSBserver/sql/mob_spell_lists.sql mob_spell_lists.sql.backup")
    print()
    print("3. Update trust_editor.py with corrected spell lists")
    print()
    print("4. Update mob_spell_lists.sql with corrected spell lists")
    print()
    print("5. Test the trusts to verify they cast correct spells!")

if __name__ == "__main__":
    main()
