#!/usr/bin/env python3
"""
Generate spell lists for each job and all job combinations.

This script creates Python dictionary definitions for spell lists that contain
all spells available to each job individually and for all possible job combinations
(main job + sub job). These can be integrated into trust_editor.py.

The spell IDs are extracted from the magic.lua enum and organized by the spell
directories they're found in (white, black, songs, ninjutsu, summoning, geomancy, blue, trust).
"""

import re
import os
from pathlib import Path
from itertools import combinations

# Job configuration
JOB_NAMES = {
    1: "WAR", 2: "MNK", 3: "WHM", 4: "BLM", 5: "RDM", 6: "THF",
    7: "PLD", 8: "DRK", 9: "BST", 10: "BRD", 11: "RNG", 12: "SAM",
    13: "NIN", 14: "DRG", 15: "SMN", 16: "BLU", 17: "COR", 18: "PUP",
    19: "DNC", 20: "SCH", 21: "GEO", 22: "RUN", 23: "MON",
}

NAME_TO_JOB = {v: k for k, v in JOB_NAMES.items()}

# Spell-type to job mapping
SPELL_TYPE_JOBS = {
    'white': [3],  # WHM
    'black': [4],  # BLM
    'songs': [10],  # BRD
    'summoning': [15],  # SMN
    'blue': [16],  # BLU
    'ninjutsu': [13],  # NIN
    'geomancy': [21],  # GEO
    'trust': list(range(1, 24)),  # All jobs can use trust
}

# Magic jobs that support custom spell lists
MAGIC_JOBS = ['WHM', 'BLM', 'RDM', 'BRD', 'SMN', 'BLU', 'NIN', 'RUN', 'GEO', 'DRK', 'PLD', 'SCH', 'BST']

def parse_magic_lua():
    """Extract spell ID to name mapping from magic.lua."""
    spell_map = {}  # spell_id -> spell_name

    magic_file = Path("/Volumes/NVMe/git/LSBserver/scripts/enum/magic.lua")
    if not magic_file.exists():
        print(f"Warning: {magic_file} not found")
        return spell_map

    content = magic_file.read_text()

    # Find xi.magic.spell section
    match = re.search(r'xi\.magic\.spell\s*=\s*\{([^}]+)\}', content, re.DOTALL)
    if match:
        section = match.group(1)
        for line_match in re.finditer(r'(\w+)\s*=\s*(\d+)', section):
            spell_name, spell_id = line_match.groups()
            spell_map[int(spell_id)] = spell_name.lower()

    return spell_map

def get_spells_by_type():
    """Get spell IDs organized by spell type directory."""
    spells_dir = Path("/Volumes/NVMe/git/LSBserver/scripts/actions/spells")
    spell_map = parse_magic_lua()

    spells_by_type = {}

    for spell_type_dir in sorted(spells_dir.iterdir()):
        if spell_type_dir.is_dir() and spell_type_dir.name not in ['.git', '__pycache__', 'trust']:
            lua_files = list(spell_type_dir.glob('*.lua'))
            spell_ids = []

            for lua_file in sorted(lua_files):
                spell_name = lua_file.stem.lower()
                # Find matching spell ID
                for spell_id, name in spell_map.items():
                    if name == spell_name:
                        spell_ids.append(spell_id)
                        break

            if spell_ids:
                spells_by_type[spell_type_dir.name] = sorted(spell_ids)

    # Add trust spells separately (all jobs can use)
    trust_dir = spells_dir / 'trust'
    if trust_dir.exists():
        lua_files = list(trust_dir.glob('*.lua'))
        spell_ids = []

        for lua_file in sorted(lua_files):
            spell_name = lua_file.stem.lower()
            for spell_id, name in spell_map.items():
                if name == spell_name:
                    spell_ids.append(spell_id)
                    break

        if spell_ids:
            spells_by_type['trust'] = sorted(spell_ids)

    return spells_by_type, spell_map

def build_job_spell_lists():
    """Build spell lists for each job."""
    spells_by_type, _ = get_spells_by_type()

    job_spell_lists = {}

    # Initialize lists for all jobs with trust spells
    for job_id in range(1, 24):
        job_name = JOB_NAMES[job_id]
        job_spell_lists[job_name] = set(spells_by_type.get('trust', []))

    # Add job-specific spells
    for spell_type, spell_ids in spells_by_type.items():
        if spell_type in SPELL_TYPE_JOBS:
            for job_id in SPELL_TYPE_JOBS[spell_type]:
                job_name = JOB_NAMES[job_id]
                job_spell_lists[job_name].update(spell_ids)

    # Convert to sorted lists
    for job_name in job_spell_lists:
        job_spell_lists[job_name] = sorted(list(job_spell_lists[job_name]))

    return job_spell_lists

def generate_python_code():
    """Generate Python code for spell lists."""
    job_spell_lists = build_job_spell_lists()

    lines = []
    lines.append("# ============================================================================")
    lines.append("# AUTO-GENERATED SPELL LISTS FOR JOBS AND JOB COMBINATIONS")
    lines.append("# Generated by generate_job_spell_lists.py")
    lines.append("# ")
    lines.append("# These lists contain spell IDs available to each job and job combination.")
    lines.append("# Single-job lists: Each job's primary spells (from spell type directories)")
    lines.append("# Combo lists: Union of both jobs' spellbooks")
    lines.append("# ============================================================================\n")

    # Single job spell lists
    lines.append("# Single Job Spell Lists")
    lines.append("# ----------------------\n")

    for job_name in sorted(MAGIC_JOBS):
        spell_ids = job_spell_lists.get(job_name, [])
        var_name = f"{job_name}_SPELLS"

        lines.append(f"{var_name} = [")
        if spell_ids:
            for i, spell_id in enumerate(spell_ids):
                if i % 12 == 0:
                    lines.append("    ")
                lines[-1] += f"{spell_id:4}, " if i < len(spell_ids) - 1 else f"{spell_id:4},"
            lines[-1] = lines[-1].rstrip(", ")
        lines.append("]")
        lines.append("")

    # Job combination spell lists
    lines.append("\n# Job Combination Spell Lists (Main Job + Sub Job)")
    lines.append("# -----------------------------------------------\n")

    for job1_name, job2_name in sorted(combinations(MAGIC_JOBS, 2)):
        combo_name = f"{job1_name}_{job2_name}_SPELLS"
        spell_ids1 = set(job_spell_lists.get(job1_name, []))
        spell_ids2 = set(job_spell_lists.get(job2_name, []))
        combined_spells = sorted(list(spell_ids1 | spell_ids2))

        lines.append(f"{combo_name} = [")
        if combined_spells:
            for i, spell_id in enumerate(combined_spells):
                if i % 12 == 0:
                    lines.append("    ")
                lines[-1] += f"{spell_id:4}, " if i < len(combined_spells) - 1 else f"{spell_id:4},"
            lines[-1] = lines[-1].rstrip(", ")
        lines.append("]")
        lines.append("")

    # Add a master dictionary for easy lookup
    lines.append("\n# Master spell list dictionary for easy lookup")
    lines.append("# Usage: JOB_SPELL_LISTS['WHM'] or JOB_SPELL_LISTS['WHM_RDM']")
    lines.append("SPELL_LISTS_BY_JOB = {")

    # Add single job lists
    for job_name in sorted(MAGIC_JOBS):
        var_name = f"{job_name}_SPELLS"
        lines.append(f"    '{job_name}': {var_name},")

    # Add combo lists
    for job1_name, job2_name in sorted(combinations(MAGIC_JOBS, 2)):
        combo_name = f"{job1_name}_{job2_name}_SPELLS"
        lines.append(f"    '{job1_name}_{job2_name}': {combo_name},")

    lines.append("}")

    return "\n".join(lines), job_spell_lists

def main():
    print("Generating spell lists for all jobs and combinations...\n")

    python_code, job_spell_lists = generate_python_code()

    # Write to output file
    output_file = Path(__file__).parent / "job_spell_lists.py"
    output_file.write_text(python_code)

    print(f"Generated: {output_file}\n")

    # Print summary
    print("Summary of generated spell lists:")
    print("-" * 70)
    print("\nSingle-Job Spell Lists:")
    for job_name in sorted(MAGIC_JOBS):
        count = len(job_spell_lists.get(job_name, []))
        spells_preview = job_spell_lists.get(job_name, [])[:5]
        print(f"  {job_name:5} - {count:3} spells (e.g., {spells_preview}...)")

    combo_count = sum(1 for _ in combinations(MAGIC_JOBS, 2))
    print(f"\nJob Combinations: {combo_count} combinations")

    print("\nExample combinations:")
    for job1_name, job2_name in sorted(combinations(MAGIC_JOBS, 2))[:5]:
        spell_ids1 = set(job_spell_lists.get(job1_name, []))
        spell_ids2 = set(job_spell_lists.get(job2_name, []))
        combined_count = len(spell_ids1 | spell_ids2)
        print(f"  {job1_name}_{job2_name:5} - {combined_count:3} spells")

    print("\nTo integrate into trust_editor.py:")
    print(f"1. Copy the contents of {output_file}")
    print("2. Paste at the top of trust_editor.py (after imports, before other definitions)")
    print("3. Update job template system to reference these lists")

if __name__ == "__main__":
    main()
