#!/usr/bin/env python3
"""
Generate SQL INSERT statements for spell lists to be added to mob_spell_lists.sql

This script creates SQL entries for all single-job and job combination spell lists,
allowing the server to recognize and use these spell lists.
"""

import re
from pathlib import Path
from itertools import combinations

# Magic jobs
MAGIC_JOBS = ['WHM', 'BLM', 'RDM', 'BRD', 'SMN', 'BLU', 'NIN', 'RUN', 'GEO', 'DRK', 'PLD', 'SCH', 'BST']

# Job names to job ID mapping
JOB_NAME_TO_ID = {
    "WAR": 1, "MNK": 2, "WHM": 3, "BLM": 4, "RDM": 5, "THF": 6,
    "PLD": 7, "DRK": 8, "BST": 9, "BRD": 10, "RNG": 11, "SAM": 12,
    "NIN": 13, "DRG": 14, "SMN": 15, "BLU": 16, "COR": 17, "PUP": 18,
    "DNC": 19, "SCH": 20, "GEO": 21, "RUN": 22, "MON": 23,
}

def parse_magic_lua():
    """Extract spell ID to name mapping from magic.lua."""
    spell_map = {}
    magic_file = Path("/Volumes/NVMe/git/LSBserver/scripts/enum/magic.lua")
    if not magic_file.exists():
        return spell_map

    content = magic_file.read_text()
    match = re.search(r'xi\.magic\.spell\s*=\s*\{([^}]+)\}', content, re.DOTALL)
    if match:
        section = match.group(1)
        for line_match in re.finditer(r'(\w+)\s*=\s*(\d+)', section):
            spell_name, spell_id = line_match.groups()
            spell_map[int(spell_id)] = spell_name.lower()

    return spell_map

def load_spell_lists():
    """Load the spell lists from trust_editor.py"""
    spell_lists = {}

    # Import from trust_editor
    import sys
    sys.path.insert(0, '/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust')

    try:
        # We can't fully import due to Tkinter, so parse the file instead
        trust_file = Path('/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust/trust_editor.py')
        content = trust_file.read_text()

        # Extract spell lists using regex
        for match in re.finditer(r'^([A-Z_]+_SPELLS)\s*=\s*\[([\d,\s]+)\]', content, re.MULTILINE):
            var_name, spell_ids_str = match.groups()
            spell_ids = [int(x.strip()) for x in spell_ids_str.split(',') if x.strip()]
            spell_lists[var_name] = spell_ids

        return spell_lists
    except Exception as e:
        print(f"Error loading spell lists: {e}")
        return {}

def generate_sql_insertions(spell_lists, start_list_id=566):
    """Generate SQL INSERT statements for all spell lists."""
    lines = []
    list_id = start_list_id
    list_id_map = {}  # Map spell list names to their SQL IDs

    # Add header comment
    lines.append("-- ============================================================================")
    lines.append("-- AUTO-GENERATED SPELL LISTS FOR JOBS AND JOB COMBINATIONS")
    lines.append("-- Generated by generate_sql_spell_lists.py")
    lines.append("-- These lists provide complete spell catalogs for each job and job combo")
    lines.append("-- ============================================================================\n")

    # Single job lists first
    lines.append("-- Single Job Spell Lists")
    lines.append("-- =====================\n")

    for job in sorted(MAGIC_JOBS):
        var_name = f"{job}_SPELLS"
        if var_name in spell_lists:
            spell_ids = spell_lists[var_name]
            list_id_map[var_name] = list_id
            list_name = job

            lines.append(f"-- {list_name} ({list_id})")
            for spell_id in spell_ids:
                # All spells available from level 1 to 99 for simplicity
                lines.append(f"INSERT INTO `mob_spell_lists` VALUES ('{list_name}',{list_id},{spell_id},1,99);")
            lines.append("")
            list_id += 1

    # Job combination lists
    lines.append("\n-- Job Combination Spell Lists (Main Job + Sub Job)")
    lines.append("-- ================================================\n")

    for job1, job2 in sorted(combinations(MAGIC_JOBS, 2)):
        var_name = f"{job1}_{job2}_SPELLS"
        if var_name in spell_lists:
            spell_ids = spell_lists[var_name]
            list_id_map[var_name] = list_id
            list_name = f"{job1}_{job2}"

            lines.append(f"-- {list_name} ({list_id})")
            for spell_id in spell_ids:
                # All spells available from level 1 to 99 for simplicity
                lines.append(f"INSERT INTO `mob_spell_lists` VALUES ('{list_name}',{list_id},{spell_id},1,99);")
            lines.append("")
            list_id += 1

    # Add summary comment
    lines.append(f"-- Total new spell lists added: {list_id - start_list_id}")
    lines.append(f"-- IDs used: {start_list_id} to {list_id - 1}")

    return "\n".join(lines), list_id_map, list_id

def main():
    print("Loading spell lists...")
    spell_lists = load_spell_lists()
    print(f"Found {len(spell_lists)} spell lists\n")

    print("Generating SQL...")
    sql_content, list_id_map, next_id = generate_sql_insertions(spell_lists)

    # Write to output file
    output_file = Path("/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust/spell_lists_for_sql.sql")
    output_file.write_text(sql_content)

    print(f"Generated SQL written to: {output_file}")
    print(f"\nSummary:")
    print(f"  Total spell lists: {len(list_id_map)}")
    print(f"  ID range: 566 to {next_id - 1}")
    print(f"  File size: {len(sql_content):,} bytes")

    # Also create a mapping file for reference
    mapping_file = Path("/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust/spell_list_id_mapping.txt")
    with open(mapping_file, 'w') as f:
        f.write("Spell List Name           -> SQL List ID\n")
        f.write("=" * 50 + "\n")
        for name in sorted(list_id_map.keys()):
            list_id = list_id_map[name]
            f.write(f"{name:30} -> {list_id}\n")

    print(f"\nID mapping file: {mapping_file}")
    print("\nNext steps:")
    print(f"1. Review the generated SQL in: {output_file}")
    print(f"2. Append the SQL to: sql/mob_spell_lists.sql")
    print(f"3. Update trust_editor.py JOB_SPELL_LISTS to reference new IDs")
    print(f"   Example: 'WHM': 566,  # Updated to use new spell list")

if __name__ == "__main__":
    main()
