#!/usr/bin/env python3
"""
Generate SQL INSERT statements for spell lists to be added to mob_spell_lists.sql

This script creates SQL entries for all single-job and job combination spell lists,
allowing the server to recognize and use these spell lists.
"""

import re
from pathlib import Path
from itertools import combinations
from collections import defaultdict

# Magic jobs
MAGIC_JOBS = ['WHM', 'BLM', 'RDM', 'BRD', 'SMN', 'BLU', 'NIN', 'RUN', 'GEO', 'DRK', 'PLD', 'SCH', 'BST']

# Job names to job ID mapping
JOB_NAME_TO_ID = {
    "WAR": 1, "MNK": 2, "WHM": 3, "BLM": 4, "RDM": 5, "THF": 6,
    "PLD": 7, "DRK": 8, "BST": 9, "BRD": 10, "RNG": 11, "SAM": 12,
    "NIN": 13, "DRG": 14, "SMN": 15, "BLU": 16, "COR": 17, "PUP": 18,
    "DNC": 19, "SCH": 20, "GEO": 21, "RUN": 22, "MON": 23,
}

# Default level ranges for spells when data is not available
# These are reasonable defaults used when spell level data is missing
DEFAULT_SPELL_LEVELS = {
    # Common spells learned early
    'early': (1, 20),      # Levels 1-20
    'mid': (20, 50),       # Levels 20-50
    'high': (50, 75),      # Levels 50-75
    'very_high': (75, 99), # Levels 75-99
}

def parse_magic_lua():
    """Extract spell ID to name mapping from magic.lua."""
    spell_map = {}
    magic_file = Path("/Volumes/NVMe/git/LSBserver/scripts/enum/magic.lua")
    if not magic_file.exists():
        return spell_map

    content = magic_file.read_text()
    match = re.search(r'xi\.magic\.spell\s*=\s*\{([^}]+)\}', content, re.DOTALL)
    if match:
        section = match.group(1)
        for line_match in re.finditer(r'(\w+)\s*=\s*(\d+)', section):
            spell_name, spell_id = line_match.groups()
            spell_map[int(spell_id)] = spell_name.lower()

    return spell_map

def extract_spell_levels():
    """Extract spell level ranges from existing Beastmen lists in mob_spell_lists.sql"""
    spell_levels = {}
    sql_file = Path('/Volumes/NVMe/git/LSBserver/sql/mob_spell_lists.sql')

    if not sql_file.exists():
        print("Warning: Could not find mob_spell_lists.sql")
        return spell_levels

    try:
        content = sql_file.read_text()
        # Extract level ranges from Beastmen lists
        for match in re.finditer(
            r"INSERT INTO `mob_spell_lists` VALUES \('Beastmen_[A-Z]+',\d+,(\d+),(\d+),(\d+)\)",
            content
        ):
            spell_id, min_level, max_level = match.groups()
            spell_id = int(spell_id)
            min_level = int(min_level)
            max_level = int(max_level)

            # Store the level range for this spell (use the range from Beastmen data)
            if spell_id not in spell_levels:
                spell_levels[spell_id] = (min_level, max_level)

        print(f"Extracted level data for {len(spell_levels)} spells from Beastmen lists")
        return spell_levels
    except Exception as e:
        print(f"Error extracting spell levels: {e}")
        return {}

def load_spell_lists():
    """Load the spell lists from trust_editor.py"""
    spell_lists = {}

    # Import from trust_editor
    import sys
    sys.path.insert(0, '/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust')

    try:
        # We can't fully import due to Tkinter, so parse the file instead
        trust_file = Path('/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust/trust_editor.py')
        content = trust_file.read_text()

        # Extract spell lists using regex
        for match in re.finditer(r'^([A-Z_]+_SPELLS)\s*=\s*\[([\d,\s]+)\]', content, re.MULTILINE):
            var_name, spell_ids_str = match.groups()
            spell_ids = [int(x.strip()) for x in spell_ids_str.split(',') if x.strip()]
            spell_lists[var_name] = spell_ids

        return spell_lists
    except Exception as e:
        print(f"Error loading spell lists: {e}")
        return {}

def generate_sql_insertions(spell_lists, spell_levels=None, start_list_id=566):
    """Generate SQL INSERT statements for all spell lists with proper level ranges."""
    if spell_levels is None:
        spell_levels = {}

    lines = []
    list_id = start_list_id
    list_id_map = {}  # Map spell list names to their SQL IDs

    # Add header comment
    lines.append("-- ============================================================================")
    lines.append("-- AUTO-GENERATED SPELL LISTS FOR JOBS AND JOB COMBINATIONS")
    lines.append("-- Generated by generate_sql_spell_lists.py with proper level ranges")
    lines.append("-- Level ranges derived from Beastmen spell lists in mob_spell_lists.sql")
    lines.append("-- ============================================================================\n")

    # Single job lists first
    lines.append("-- Single Job Spell Lists")
    lines.append("-- =====================\n")

    stats = {'with_levels': 0, 'without_levels': 0}

    for job in sorted(MAGIC_JOBS):
        var_name = f"{job}_SPELLS"
        if var_name in spell_lists:
            spell_ids = spell_lists[var_name]
            list_id_map[var_name] = list_id
            list_name = job

            lines.append(f"-- {list_name} ({list_id})")
            for spell_id in spell_ids:
                # Use extracted level data if available, otherwise use reasonable defaults
                if spell_id in spell_levels:
                    min_lvl, max_lvl = spell_levels[spell_id]
                    stats['with_levels'] += 1
                else:
                    # Default: spells available from level 1 to 99
                    min_lvl, max_lvl = 1, 99
                    stats['without_levels'] += 1
                lines.append(f"INSERT INTO `mob_spell_lists` VALUES ('{list_name}',{list_id},{spell_id},{min_lvl},{max_lvl});")
            lines.append("")
            list_id += 1

    # Job combination lists
    lines.append("\n-- Job Combination Spell Lists (Main Job + Sub Job)")
    lines.append("-- ================================================\n")

    for job1, job2 in sorted(combinations(MAGIC_JOBS, 2)):
        var_name = f"{job1}_{job2}_SPELLS"
        if var_name in spell_lists:
            spell_ids = spell_lists[var_name]
            list_id_map[var_name] = list_id
            list_name = f"{job1}_{job2}"

            lines.append(f"-- {list_name} ({list_id})")
            for spell_id in spell_ids:
                # Use extracted level data if available
                if spell_id in spell_levels:
                    min_lvl, max_lvl = spell_levels[spell_id]
                    stats['with_levels'] += 1
                else:
                    min_lvl, max_lvl = 1, 99
                    stats['without_levels'] += 1
                lines.append(f"INSERT INTO `mob_spell_lists` VALUES ('{list_name}',{list_id},{spell_id},{min_lvl},{max_lvl});")
            lines.append("")
            list_id += 1

    # Add summary comment
    lines.append(f"-- Total new spell lists added: {list_id - start_list_id}")
    lines.append(f"-- IDs used: {start_list_id} to {list_id - 1}")
    lines.append(f"-- Spells with level data: {stats['with_levels']}")
    lines.append(f"-- Spells without level data (using defaults): {stats['without_levels']}")

    return "\n".join(lines), list_id_map, list_id, stats

def main():
    print("Loading spell lists...")
    spell_lists = load_spell_lists()
    print(f"Found {len(spell_lists)} spell lists\n")

    print("Extracting spell level ranges...")
    spell_levels = extract_spell_levels()

    print("\nGenerating SQL with proper level ranges...")
    sql_content, list_id_map, next_id, stats = generate_sql_insertions(spell_lists, spell_levels)

    # Write to output file
    output_file = Path("/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust/spell_lists_for_sql.sql")
    output_file.write_text(sql_content)

    print(f"Generated SQL written to: {output_file}")
    print(f"\nSummary:")
    print(f"  Total spell lists: {len(list_id_map)}")
    print(f"  ID range: 566 to {next_id - 1}")
    print(f"  File size: {len(sql_content):,} bytes")
    print(f"  Spells with extracted level data: {stats['with_levels']:,}")
    print(f"  Spells using defaults: {stats['without_levels']:,}")

    # Also create a mapping file for reference
    mapping_file = Path("/Volumes/NVMe/git/LSBserver/scripts/actions/spells/trust/spell_list_id_mapping.txt")
    with open(mapping_file, 'w') as f:
        f.write("Spell List Name           -> SQL List ID\n")
        f.write("=" * 50 + "\n")
        for name in sorted(list_id_map.keys()):
            list_id = list_id_map[name]
            f.write(f"{name:30} -> {list_id}\n")

    print(f"\nID mapping file: {mapping_file}")
    print("\nNext steps:")
    print(f"1. Review the generated SQL in: {output_file}")
    print(f"2. IMPORTANT: Replace the spell list entries in sql/mob_spell_lists.sql")
    print(f"   - Remove all entries for list IDs 566-656 (the new job spell lists)")
    print(f"   - Append the corrected SQL from {output_file}")
    print(f"3. Verify the database loads correctly after updates")

if __name__ == "__main__":
    main()
